In [ ]:
# if you have a null value in data set this will help to clean those null values using mean and median in scikit learn

In [2]:
import pandas as pd
import numpy as np
data = pd.DataFrame({'age':[20, 21, 19, 18, np.nan, 22, 23, np.nan], 'salary':[1000, 2000, 3000, 4000, 5000, np.nan, 7000, 8000]})

data

,age,salary
0,20.0,1000.0
1,21.0,2000.0
2,19.0,3000.0
3,18.0,4000.0
4,NaN,5000.0
5,22.0,NaN
6,23.0,7000.0
7,NaN,8000.0


In [3]:
data.isna().sum()

age       2
salary    1
dtype: int64

In [ ]:
# using simple imputer to fill the null values in data set with mean 
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
imputer.fit_transform(data)

array([[  20.        , 1000.        ],
       [  21.        , 2000.        ],
       [  19.        , 3000.        ],
       [  18.        , 4000.        ],
       [  20.5       , 5000.        ],
       [  22.        , 4285.71428571],
       [  23.        , 7000.        ],
       [  20.5       , 8000.        ]])

In [ ]:
# using simple imputer to fill the null values in data set with median 
imputer = SimpleImputer(strategy='mean')
imputer.fit_transform(data)

array([[  20.        , 1000.        ],
       [  21.        , 2000.        ],
       [  19.        , 3000.        ],
       [  18.        , 4000.        ],
       [  20.5       , 5000.        ],
       [  22.        , 4285.71428571],
       [  23.        , 7000.        ],
       [  20.5       , 8000.        ]])

In [ ]:
# using simple imputer to fill the null values in data set with most frequent value
imputer = SimpleImputer(strategy='most_frequent')
imputer.fit_transform(data)

array([[  20., 1000.],
       [  21., 2000.],
       [  19., 3000.],
       [  18., 4000.],
       [  18., 5000.],
       [  22., 1000.],
       [  23., 7000.],
       [  18., 8000.]])

In [11]:
imputer = SimpleImputer(strategy='constant', fill_value=10)
imputer.fit_transform(data)

array([[  20., 1000.],
       [  21., 2000.],
       [  19., 3000.],
       [  18., 4000.],
       [  10., 5000.],
       [  22.,   10.],
       [  23., 7000.],
       [  10., 8000.]])

In [13]:
names = pd.DataFrame({'name':['John', 'Mike', 'Sarah', 'Jessica', np.nan, 'David', 'Emily', np.nan]})
names

,name
0,John
1,Mike
2,Sarah
3,Jessica
4,NaN
5,David
6,Emily
7,NaN


In [21]:
imputer = SimpleImputer(strategy='constant', fill_value='Messi', add_indicator=True)
imputer.fit_transform(names)


array([['John', False],
       ['Mike', False],
       ['Sarah', False],
       ['Jessica', False],
       ['Messi', True],
       ['David', False],
       ['Emily', False],
       ['Messi', True]], dtype=object)